#!/usr/bin/env sh

# check if brew is executable
if ! test -x "$(command -v brew)"; then
  echo 'Error: brew is not installed' >&2
  exit 1
fi

# karabiner
if ! test -x /Applications/Karabiner-Elements.app; then
  brew cask install karabiner-elements
fi
if ! test -x "$(command -v goku)"; then
  brew install yqrashawn/goku/goku
fi
ln -sf $PWD/karabiner.edn ~/.config/karabiner.edn
echo "Update Karabiner config: "
goku
